sudo: required
language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install --progress-bar off .[tensorflow-cpu]
  - pip install flake8
  - pip install pytest

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings. Texar limits lines to a maximum of 80 chars. 
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics

script:
  # Unit tests
  - pytest

notifications:
  email: false
